[package]
name = "concurrency_blk_a"
version = "0.0.1"
authors = ["CRIMX <straybugs@gmail.com>"]
description = "Add one"
edition = "2021"

[dependencies]
oocana_sdk = { path = "../../../sdk" }
tokio = { version = "1.28.2", features = ["full"] }