[package]
name = "pkg_v"
version = "0.30.25"
authors = ["CRIMX <straybugs@gmail.com>"]
description = "Add one"
edition = "2021"

[dependencies]
oocana_sdk = { path = "../../../../../../sdk" }
tokio = { version = "1.44.2", features = ["full"] }