[package]
name = "manifest_meta"
version = "0.30.11"
authors = ["CRIMX <straybugs@gmail.com>"]
description = "Oocana block meta"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
layer = { path = "../layer" }
manifest_reader = { path = "../manifest_reader" }
tracing = "0.1.40"