[package]
name = "identity"
version = "0.0.1"
authors = ["CRIMX <straybugs@gmail.com>"]
description = "output the input value"
edition = "2021"

[dependencies]
oocana_sdk = { path = "../../../sdk" }
tokio = { version = "1.28.2", features = ["full"] }